- testfile.m2
> added test file

- Visualize.m2
- Visualize/js/visGraph2d.js
- Visualize/templates/visGraph/js/visGraph2d.js
- Visualize/templates/visGraph/visGraph-template.html
- server-stuff/server.m2
isCM works but still needs the right input (integers as vertex labels). This should work with the M2 visualize(Graph), but the `M2 Talky` button is broken. It is a good start though.
> isCM talks to server

- Visualize.m2
- Visualize/js/visGraph2d.js
- Visualize/templates/visGraph/visGraph-template.html
Added isBipartite and isChordal. I also cleaned up the templates so it is easier to add methods. In order to add a method in the side bar, you need to edit 
* `visGraph-template.html`, (more detailed instructions are found here);
* `openGraphServer()` in `Visualize.m2`;
* `visGraph2d.js`;
> Bstone graph parity

- Visualize/templates/visDigraph/visDigraph-template.html
Trivial change to visDigraph-template.html.
> Changed a file

- Visualize.m2
Created a better documentation structure. Of course more work needs to be done.
> Documentation branden

- Visualize/js/visGraph2d.js
Minor fix - Commented out a few lines related to highlighting neighbors for now so that the code works
> Vis graph brett

- #Visualize.m2#
- .#Visualize.m2
- Visualize/js/visGraph2d.js
- Visualize/templates/visGraph/visGraph-template.html
Added highlighting neighbors in graphs and "End Session" now becomes "Session Terminated" once the user has terminated the session.
> Added neighbor highlighting

- Visualize/js/visGraph2d.js
> Minor edit to path for clipboard image

- .#Visualize.m2
- Visualize/js/visGraph2d.js
> Fixed an issue with deleting vertices

- Visualize.m2
There was an issue with the path. If a user had an instance of M2 open in a directory other than the one containing `Visualize.m2`, then the package would not know what to do. I fixed this by creating a global variable `basePath = currentFileDirectory`.
> Path issues

- Visualize.m2
Condensed `openGraphServer` to `openServer`.
> created openServer

- Visualize.m2
- Visualize/js/visPoset.js
- Visualize/templates/visPoset/visPoset-template.html
Added lots of functions to do computations with posets, such as computing ranking functions, height functions, maximal chains, etc.  These will be important if we want to edit the poset on the fly without having to export it back to M2 every time to recompute the ranks of the elements.  Also changed the poset2M2Constructor() function and made some changes to what Visualize.m2 is exporting to the poset-template html file.
> Many new poset functions

- Visualize.m2
- Visualize/js/visGraph2d.js
- Visualize/js/visPoset.js
- Visualize/templates/visGraph/visGraph-template.html
- Visualize/templates/visPoset/visPoset-template.html
Fixed an issue with labels not exporting correctly as strings to the visPoset html template.  Added isComparabilityGraph as a boolean test in visGraph.  This method is provided by Posets.m2.  Finally, I added back in some of the side menu stuff in visPoset, primarily the boolean tests and numerical invariant drop-down menus.
> Added tests to visPoset

- Visualize.m2
- Visualize/js/visDigraph2d.js
- Visualize/js/visPoset.js
Added all boolean tests for posets into the openServer method.  Also modified openServer to use the exact constructor passed in from the html file, which should now be okay since the user can only type alphanumeric characters for node names.  Fixed a lot of things in visDigraph (m2 constructor, initializeBuilder, resize window, etc.) so it should now be working better.
> Added poset tests to m2 file and various digraph fixes

- Visualize/js/visDigraph2d.js
- Visualize/js/visGraph2d.js
- Visualize/js/visPoset.js
- Visualize/templates/visDigraph/visDigraph-template.html
- Visualize/templates/visPoset/visPoset-template.html
Posets can now be edited.  Some code has also been cleaned up and some more comments were added.
> Poset editing implemented

- Visualize/js/visPoset.js
- Visualize/templates/visPoset/visPoset-template.html
Added options to show/hide node labels and to fix the extremal nodes in the poset.  Also fixed some issues with highlighting comparable elements.
> Additions to visPoset

- Visualize/js/visDigraph2d.js
- Visualize/js/visGraph2d.js
- Visualize/js/visPoset.js
- Visualize/templates/visDigraph/visDigraph-template.html
- Visualize/templates/visGraph/visGraph-template.html
Added sliders for force variables and option to show/hide labels to visGraph and visDigraph.  Also fixed where the export TikZ div should be added when Export TikZ is clicked.
> Updates to visGraph and visDigraph

- Visualize/js/visDigraph2d.js
- Visualize/js/visGraph2d.js
- Visualize/js/visPoset.js
- Visualize/templates/visDigraph/visDigraph-template.html
- Visualize/templates/visGraph/visGraph-template.html
- Visualize/templates/visPoset/visPoset-template.html
Fixed some issues with resizing the svg when the window is resized, and addressed Branden's issue of the nodes being able to go behind the side menu.
> Updates to window resizing

- Visualize.m2
- Visualize/js/visGraph2d.js
- Visualize/js/visSimplicialComplex2d-old.js
- Visualize/js/visSimplicialComplex2d.js
- Visualize/templates/visDigraph/visDigraph-template.html
- Visualize/templates/visPoset/visPoset-template.html
- Visualize/templates/visSimplicialComplex/visSimplicialComplex2d-template-old.html
- Visualize/templates/visSimplicialComplex/visSimplicialComplex2d-template-old2.html
- Visualize/templates/visSimplicialComplex/visSimplicialComplex2d-template.html
Implemented visualizations of 2d simplicial complexes.  This now has essentially all of the same functionality as the other visualization templates (names, showing/hiding labels, highlighting connected stuff, running tests, force variables, editing nodes and edges, etc.) minus the ability to edit 2-dimensional faces, which is my next goal.
> Updated to visSimplicialComplex

- Visualize.m2
- Visualize/js/visGraph2d.js
- Visualize/templates/visGraph/visGraph-template.html
Added isRigid functionality for work with graphs in M2 version 1.9.1.
> Tom is rigid

- Visualize/js/visDigraph2d.js
- Visualize/js/visGraph2d.js
- Visualize/js/visPoset.js
- Visualize/js/visSimplicialComplex2d.js
- Visualize/templates/visDigraph/visDigraph-template.html
- Visualize/templates/visGraph/visGraph-template.html
- Visualize/templates/visPoset/visPoset-template.html
Should no longer have the offsetLeft or bootSideMenu errors... maybe?
> Attempting to fix issue #110

- Visualize/js/visSimplicialComplex2d.js
Fixed an issue about the points for a simplicial complex initially being set to "undefined" in chrome and safari.
> Fixed issue #110

- Visualize.m2
- Visualize/css/common.css
- Visualize/js/visDigraph2d.js
- Visualize/js/visGraph2d.js
- Visualize/js/visPoset.js
- Visualize/js/visSimplicialComplex2d.js
Fixed most of the issues 145-152.
> Fixed recently discovered issues
